config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "posts#index"
  resource :timeline, only: [:show]
  resource :profile, only: [:show, :edit, :update]

  resources :posts, only: [:new, :create, :index, :show]
  resources :accounts, only: [:show] do
    resource :following, only: [:show]
    resource :follower, only: [:show]
  end


  namespace :api ,defaults: { format: :json } do
    scope '/accounts/:account_id' do
      resource :follow, only: [:create, :show]
      resource :unfollow, only: [:create]
    end

    scope '/posts/:post_id' do
      resource :like, only: [:create, :destroy, :show]
      resources :comments, only: [:create, :index]
    end

  end

end

app/views/common/_index_posts.html.haml
- posts .each do |post|
  .card.post-index{data: {post_id: post.id}}
    .postedUser
      = link_to account_path(post.user) do
        = image_tag post.user.profile.avatar, class: 'postedUser_avatar'
      .postedUser_textContainer
        %p.postedUser_username= post.user.username
        %p.postedUser_postTime= show_posttime(post)

    .card_images
      - post.images.each do |image|
        = image_tag image

    %p.card_caption= post.caption

    .card_actions
      = image_tag 'likeBtn', class: ' card_actionItem hidden', id: "likeBtn_#{post.id}"
      = image_tag 'unlikeBtn', class: 'card_actionItem hidden', id: "unlikeBtn_#{post.id}"

      = link_to post_path(post) do
        = image_tag 'commentBtn', class: 'card_actionItem'

      = link_to "https://twitter.com/intent/tweet?url=#{URI.encode_www_form_component(request.original_url)}&text=#{URI.encode_www_form_component(post.caption)}", rel: 'nofollow', target: '_blank' do
        = image_tag 'shareBtn', class: 'card_actionItem'

app/views/common/_show_accounts_list.html.haml
- users.each do |user|
  .accountsList
    .accountsList_avatar
      = image_tag user.profile.avatar
    .accountsList_username
      = user.username

app/views/common/_tabs.html.haml
.tabs
  .tabs_item{ class: "#{set_active(root_path)}" }
    = link_to 'All Posts', root_path
  .tabs_item{ class: "#{set_active(timeline_path)}" }
    = link_to 'タイムライン', timeline_path

app/views/common/_user_detail.html.haml
.profileNumbers
  .profileNumbers_item
    %p.profileNumbers_number= user.posts.length
    %p.profileNumbers_label Posts
  .profileNumbers_item
    = link_to account_follower_path(account_id: user.id) do
      %p.profileNumbers_number#followersCount= user.followers.length
      %p.profileNumbers_label Followers
  .profileNumbers_item
    = link_to account_following_path(account_id: user.id) do
      %p.profileNumbers_number= user.followings.length
      %p.profileNumbers_label Followings